### ISSUE TITLE
Add year.

### ISSUE THREAD

**Issue by jhuerta6** [ulimartinez/movie-night-back#4]
Hello there,

I think a nice feature would be to add the year into the information pertaining to the kinoes.

Thank you.

Best regards, 
jhuerta6 

Edit: I wanted to add a label to mark this as an enhancement.

**Comment by ulimartinez** [comment]
Fixed this in commit https://github.com/ulimartinez/movie-night-back/commit/e610fba1bb12958ca0604f1fcf7b984e2b4a7621
